# Rate Limit
service.sec=10000
service.limit=100

# Server
server.port=2441
http.port=2081
server.ssl.key-store=classpath:server.p12
server.ssl.key-store-password=123456

# JKS or PKCS12
server.ssl.keyStoreType=PKCS12

# Datasource connection properties
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bsd_api_rec_member?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=P@55w0rd
spring.jpa.show-sql=false

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=validate

# LOGGING
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.api.dms.member=INFO
logging.file.name=bsd_api_rec_member.log
logging.file.max-history=10
logging.file.max-size=200MB
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n

# Mailjet
mailjet.email=ana@amplifio.tech
mailjet.name=Amplifio

# Services
services.domain=app.amplifio.tech
services.bsd.api.rec.auth=http://localhost:2080/
services.bsd.api.rec.departments=http://localhost:2082/

# UserService
service.user.getuser.userok=Ok.
service.user.getuser.notfound=Not found.
service.user.putupdate.userupdated=User updated.
service.user.putupdate.emailnotfound=Email not found.
service.user.postadd.emailalreadyexist=Email already exists : 
service.user.postadd.usercreated=User created.
service.user.postadd.notfound=Not found.
service.user.postregister.usercreated=User created. Please check your email for confirmation.
service.user.postregister.notfound=Not found.
service.user.postregister.notagree=User not agree to policy and terms
service.user.postregister.emailalreadyexist=Email already exist : 
service.user.postedit.userupdated=User created.
service.user.postedit.notfound=Not found.
service.user.postuserchange.ok=Ok.
service.user.postuserchange.notfound=Not found.
service.user.postnotify.notified=User notified. Please check your email inbox for verification.
service.user.postnotify.notifypending=User notification pending.
service.user.postnotify.noemail=No email template.
service.user.postnotify.datanotfound=Data not found or already notified.
service.user.postconfirmation.postconfirmation=User confirmed. You can start to use all of our functions.
service.user.postconfirmation.datanotfound=Data not found or already confirmed.

# Paypall
paypall.client_id=Ae3-Xtq7YMEO1QEoXJghga4nQOWL50Odcq9sH69CkJkI0jLlndgTucTGorGdQgJj8P3hyfBEHCSo7Y9g
paypall.client_secret=EJrIO_RgI1om9RKGXgim0x4yCt47no7uP1MyZ1yLjnllOOcNrA4hLQhhpr-rAmWYqgiNmioct4VgjYJy

# PaymentService
service.payment.postadd.ok=Payment Completed.
service.payment.postadd.notfound=Payment Not found.