CREATE or REPLACE TABLE tb_resume (
  tbr_id int(11) NOT NULL AUTO_INCREMENT,
  tbr_create_date datetime DEFAULT NULL,
  tbr_create_id int(11) DEFAULT NULL,
  tbr_create_idc int(11) DEFAULT NULL,
  tbr_update_date datetime DEFAULT NULL,
  tbr_update_id int(11) DEFAULT NULL,
  tbr_data_name_raw VARCHAR(255),
  tbr_data_name_first VARCHAR(255),
  tbr_data_name_last VARCHAR(255),
  tbr_data_name_middle VARCHAR(255),
  tbr_data_name_title VARCHAR(255),
  tbr_data_phoneNumbers JSON,
  tbr_data_websites JSON,
  tbr_data_emails JSON,
  tbr_data_dateOfBirth VARCHAR(255),
  tbr_data_location_formatted VARCHAR(255),
  tbr_data_location_postalCode VARCHAR(255),
  tbr_data_location_state VARCHAR(255),
  tbr_data_location_country VARCHAR(255),
  tbr_data_location_countryCode VARCHAR(255),
  tbr_data_location_rawInput VARCHAR(255),
  tbr_data_location_streetNumber VARCHAR(255),
  tbr_data_location_street VARCHAR(255),
  tbr_data_location_apartmentNumber VARCHAR(255),
  tbr_data_location_city VARCHAR(255),
  tbr_data_objective VARCHAR(255),
  tbr_data_languages JSON,
  tbr_data_languageCodes JSON,
  tbr_data_summary VARCHAR(255),
  tbr_data_totalYearsExperience int(11),
  tbr_data_headShot VARCHAR(255),
  tbr_data_education JSON,
  tbr_data_profession VARCHAR(255),
  tbr_data_linkedin VARCHAR(255),
  tbr_data_workExperience JSON,
  tbr_data_skills JSON,
  tbr_data_certifications JSON,
  tbr_data_publications JSON,
  tbr_data_referees JSON,
  tbr_data_sections JSON,
  tbr_data_isResumeProbability int(11),
  tbr_data_rawText VARCHAR(255),
  tbr_meta_identifier VARCHAR(255),
  tbr_meta_fileName VARCHAR(255),
  tbr_meta_ready int(11),
  tbr_meta_readyDt VARCHAR(255),
  tbr_meta_failed int(11),
  tbr_meta_expiryTime VARCHAR(255),
  tbr_meta_language VARCHAR(255),
  tbr_meta_pdf VARCHAR(255),
  tbr_meta_parentDocument_identifier VARCHAR(255),
  tbr_meta_childDocuments JSON,
  tbr_meta_pages JSON,
  tbr_meta_isVerified int(11),
  tbr_meta_reviewUrl VARCHAR(255),
  tbr_meta_ocrConfidence DOUBLE,
  tbr_error_errorCode VARCHAR(255),
  tbr_error_errorDetail VARCHAR(255),
  PRIMARY KEY (tbr_id)
);