# Rate Limit
service.sec=10000
service.limit=100

# Server
server.port=2442
http.port=2082
server.ssl.key-store=classpath:server.p12
server.ssl.key-store-password=123456

# JKS or PKCS12
server.ssl.keyStoreType=PKCS12

# Datasource connection properties
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bsd_api_rec_departments?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=P@55w0rd
spring.jpa.show-sql=false

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=validate

# LOGGING
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.api.dms.departments=INFO
logging.file.name=bsd_api_rec_departments.log
logging.file.max-history=10
logging.file.max-size=200MB
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n

# Services
services.bsd.api.rec.auth=http://localhost:2080/
services.bsd.api.rec.member=http://localhost:2081/

# File
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.dir=c:/tmp/
file.resume.dir=C:/xampp/htdocs/resume/

# Key
collection.affinda=npCUUqHs
workspace.affinda=XMLYhWVf
key.affinda=8d3d286d8d2550fcf982a0840671fed710b719cd